### ISSUE TITLE
midjourney-proxy目前支持railway部署

### ISSUE THREAD

**Issue by ymeimei** [Git-HandClup/plugin_midjourney#6]
用railway部署以后回调地址和redis地址应该怎么修改呢

**Comment by Git-HandClup** [comment]
midjourney-proxy只是单独的一个服务，你直接通过railway部署即可，不需要再进行修改其他文件，回调地址是指你在每次请求midjourney-proxy的接口时需要携带的一个参数，redis地址也是直接修改mj.py文件中的redis配置，跟midjourney-proxy无关

**Comment by Git-HandClup** [comment]
> 用railway部署以后回调地址和redis地址应该怎么修改呢

目前插件已更新成最终版本，不需要回调地址和redis，只需要正常提供midjourney-proxy的地址到配置文件即可

**Comment by ymeimei** [comment]
谢谢作者的解答和更新，目前可正常使用

**Comment by ymeimei** [comment]
> midjourney-proxy只是单一的一个服务，你直接通过railway部配置即可，不需要再行修改其他文件，回调地址是指你在每次请求midjourney-proxy的接口时需要携带的一个参数，redis地址也是直连修改mj.py文件中的redis配置，跟midjourney-proxy无关

谢谢作者大大的解答和更新，目前可正常使用
